MESSAGE_ID_KEY = "MESSAGE_ID_KEY"
KARMA_SCORE_KEY = "KARMA_SCORE_KEY"
FULL_PROCESSED_USER_TEXT_KEY = "FULL_PROCESSED_USER_TEXT"
DICT_OF_RESULTS_KEY = "DICT_OF_RESULTS"
LIST_OF_PROCESSED_DATA_DICTS_KEY = "LIST_OF_PROCESSED_DATA_DICTS"
TEXT_FOR_TOXIC_PROCESSING_KEY = "TEXT_FOR_TOXIC_PROCESSING"
MESSAGE_TEXT_KEY = "MESSAGE_TEXT"
POSITIVE_COEFFICIENT_KEY = "POSITIVE_COEFFICIENT"
NEGATIVE_COEFFICIENT_KEY = "NEGATIVE_COEFFICIENT"
NEUTRAL_COEFFICIENT_KEY = "NEUTRAL_COEFFICIENT"
CONNECTION_COEFFICIENT_KEY = "CONNECTION_COEFFICIENT"

CUTIE_MODE_ID = 0
AVERAGE_MODE_ID = 1
MORGENSHTERN_MODE_ID = 2

