MESSAGE_ID_KEY = "MESSAGE_ID_KEY"
KARMA_SCORE_KEY = "KARMA_SCORE_KEY"
MESSAGE_TEXT_KEY = "MESSAGE_TEXT"
POSITIVE_COEFFICIENT_KEY = "POSITIVE_COEFFICIENT"
NEGATIVE_COEFFICIENT_KEY = "NEGATIVE_COEFFICIENT"
NEUTRAL_COEFFICIENT_KEY = "NEUTRAL_COEFFICIENT"
CONNECTION_COEFFICIENT_KEY = "CONNECTION_COEFFICIENT"

CUTIE_MODE_ID = 0
AVERAGE_MODE_ID = 1
MORGENSHTERN_MODE_ID = 2

